simplify amsi resource url
phra/metasploit-framework pull request #4
Opened 2019-12-17 09:40 UTC by timwr

I think this is simpler

2019-12-17 11:19 UTC, phra requested changes

2019-12-17 11:19 UTC, phra commented on lib/msf/core/exploit/http/server.rb
> -    @service_path = opts['Path'] || random_uri
this is fixing the `generate random uri if not provided` logic in `add_resource`.
i suggest to leave it as proposed.

2019-12-17 11:19 UTC, phra commented on modules/exploits/multi/script/web_delivery.rb
> +    elsif request.raw_uri.to_s.ends_with?('.psh')
there is already some code dedicated to serving files over http(s) that is `http_server.rb` via the exposed `add_resource` function.

i would prefer to reuse existing logic instead of adding custom `if`s to the `web_delivery` module itself.

2019-12-17 11:19 UTC, phra commented on modules/exploits/multi/script/web_delivery.rb
> +        amsi_uri = uri + '.psh'
this will make the request easy to be flagged since `.psh` is not a common extensions used on the internet. i personally prefer the `random_uri` approach.

2020-02-14 22:07 UTC, phra commented on lib/msf/core/exploit/http/server.rb
> +    @service_path = opts['Path']
```suggestion
```

2020-02-17 08:53 UTC, Tomy0498 approved these changes

2020-02-17 15:12 UTC, phra approved these changes

2020-02-17 15:12 UTC, merged